### PR TITLE
Implement multifile upload to transaction page

### PR DESCRIPTION
**Pull request by cf12**
Split PR from #4:
- Implements multiple file uploads & adds receipt section to `/admin/transactions/:id`
- Windows paths have `\\`, which messes up the file upload paths, so file paths are normalized to unix (doesn't matter too much since prod is probably not Windows so ¯\\(ツ)/¯)

### CODE REVIEW

**Comment by itsmingjie** [comment]
And RE: prod yeah prod is a Docker image over ubuntu 1804. And ew Windows :)

**Comment by cf12** [comment]
¯\\(ツ)/¯

**Comment by itsmingjie** [comment]
Update: Reviewing this weekend. I suspect that I'll need to modify the way we're currently pulling information from Airtable for this change to go through since currently, the client-side has zero knowledge of the metadata required to keep previously updated files in Airtable. 

Notes for self (& @CF12 if time) -- most changes should happen within https://github.com/executebig/goblin/blob/8553d0e2c41061f3ca408716022f7d1cae15eb47/src/services/airtable.js#L97-L104, as we need to make sure the server feeds the client the full "file" object (most importantly, the `id`). 

The file upload command cannot be executed directly after we upload one file. We have to implement a "finish" button, and then our server should generate an array of attachment objects **INCLUDING** all previously uploaded files that are not deleted, as well as all new files uploaded with their temporary URLs. These files can only be deleted after the bulk upload job has been executed **OR** the client closed the connection (exited page, etc.). 

This needs a lot more thinking...

**Comment by cf12** [comment]
Yeah, I think that makes a lot of sense. We can probably fetch all the existing receipts as we load the tx, and cache those client side until the client submits / finishes their changes. That'll make it easy for us to also add capabilities for removing and reordering receipts if we want.

**Comment by itsmingjie** [comment]
OR we run a server-side script that combines all files into one PDF file /s

**Comment by cf12** [comment]
NOW WE'RE TALKIN

**Comment by itsmingjie** [comment]
@CF12 Upload logic changed here. Highly recommend rebasing this from the current HEAD. See #9

**Comment by itsmingjie** [comment]
Closing this in favor of commit 041474d3d7b9b9e157bd24fd58397f33f1c7398c and beyond as we move to Peter Pan managed uploads.

**Pull request closed without merging**
